name: Tests

on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Instal package from local files
        run: python3 -m pip install .
        env:
          CONDUCTOR_PYTHON_VERSION: v1.0.0
      - name: Run Unit Tests
        run: python3 -m unittest discover --verbose --start-directory=./tests/unit
      - name: Run Integration Tests
        run: python3 ./tests/main.py
        env:
          PYTHON_INTEGRATION_TESTS_SERVER_API_URL: ${{ secrets.PYTHON_INTEGRATION_TESTS_SERVER_API_URL }}
          PYTHON_INTEGRATION_TESTS_SERVER_KEY_ID: ${{ secrets.PYTHON_INTEGRATION_TESTS_SERVER_KEY_ID }}
          PYTHON_INTEGRATION_TESTS_SERVER_KEY_SECRET: ${{ secrets.PYTHON_INTEGRATION_TESTS_SERVER_KEY_SECRET }}
